//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QTaxi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car
    {
        public Car()
        {
            this.Order = new HashSet<Order>();
            this.TaxiCars = new HashSet<TaxiCars>();
        }
    
        public int Id { get; set; }
        public string car_mark { get; set; }
        public string car_model { get; set; }
        public string number { get; set; }
        public Nullable<int> status_id { get; set; }
        public Nullable<int> driver_id { get; set; }
        public string owner_user_id { get; set; }
    
        public virtual ICollection<Order> Order { get; set; }
        public virtual ICollection<TaxiCars> TaxiCars { get; set; }
        public virtual CarStatus CarStatus { get; set; }
        public virtual User AspNetUsers { get; set; }
        public virtual Driver Driver { get; set; }
    }
}
