//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QTaxi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int id { get; set; }
        public string address_from { get; set; }
        public string address_to { get; set; }
        public Nullable<int> taxi_id { get; set; }
        public Nullable<int> car_id { get; set; }
        public Nullable<int> client_id { get; set; }
        public string client_phone { get; set; }
        public string client_name { get; set; }
        public Nullable<int> status_id { get; set; }
        public Nullable<double> address_from_lat { get; set; }
        public Nullable<double> address_from_lon { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
        public string manager_user_id { get; set; }
    
        public virtual Car Car { get; set; }
        public virtual OrderStatus OrderStatus { get; set; }
        public virtual Taxi Taxi { get; set; }
        public virtual User AspNetUsers { get; set; }
    }
}
