//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QTaxi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaxiCars
    {
        public int id { get; set; }
        public int taxi_id { get; set; }
        public int car_id { get; set; }
    
        public virtual Car Car { get; set; }
        public virtual Taxi Taxi { get; set; }
    }
}
