//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QTaxi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Taxi
    {
        public Taxi()
        {
            this.Order = new HashSet<Order>();
            this.TaxiCars = new HashSet<TaxiCars>();
        }
    
        public int Id { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public string phone { get; set; }
    
        public virtual ICollection<Order> Order { get; set; }
        public virtual ICollection<TaxiCars> TaxiCars { get; set; }
    }
}
